site=ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre
version=8.30
package=pcre-$(version).tar.gz
workdir=$(CACHE_DIR)/pcre-$(version)

.PHONY: default
default: install

$(CACHE_DIR):
	mkdir $(CACHE_DIR)

$(CACHE_DIR)/$(package): | $(CACHE_DIR)
	curl -o $@ "$(site)/$(package)"

$(BUILD_DIR):
	mkdir $(BUILD_DIR)

$(workdir): $(CACHE_DIR)/$(package) | $(BUILD_DIR)
	tar -C $(dir $@) -zxf "$<"

.PHONY: configure
configure: | $(workdir)
	cd $(workdir); ./configure --prefix=$(BUILD_DIR)

.PHONY: compile
compile: | configure
	make -C $(workdir)

.PHONY: install
install: | compile
	make -C $(workdir) install
